seoulhotver2/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'subway/', include('subway.urls')),
]

subway/urls.py
from django.conf.urls import url, include
from .views import SubwayLV, subway_lazy, subway_now,main,bsbusy,bsempty,bsmy,bsvs,bscm,bsfd,bsch,bssh,pnpn

app_name='subway'
urlpatterns = [
    url(r'^$', main, name='index'),
    url(r'busy/$', SubwayLV, name='busy'),
    url(r'lazy/$', subway_lazy, name='lazy'),
    url(r'now/$', subway_now, name='now'),

    url(r'1bz/$', bsbusy, name='1bz'),
    url(r'2em/$', bsempty, name='2em'),
    url(r'3my/$', bsmy, name='3my'),
    url(r'4vs/$', bsvs, name='4vs'),
    url(r'5cm/$', bscm, name='5vs'),
    url(r'6fd/$', bsfd, name='6fd'),
    url(r'chat/$', bsch, name='chat'),
    url(r'search/$', bssh, name='search'),
    url(r'pn/(?P<z>.*)/(?P<x>.*)/$', pnpn, name='sms'),
]

subway/models.py
from django.db import models

# Create your models here.

ON_OFF = (
    ('on', '승차'),
    ('off', '하차'),
    )


class SubwayModelQuerset(models.query.QuerySet):
    pass

class SubwayModelManager(models.Manager):
        pass

class SubwayModel(models.Model):
    ''' Seoul Hot place Subway model'''

    date = models.DateField(
                default='2017-01-01',
                verbose_name='date'
                )

    station = models.CharField(
                max_length=100,
                verbose_name='station',
                )

    line_number = models.CharField(
                max_length=10,
                default='1호선',
                verbose_name='subway line'
                )

    population0 = models.IntegerField(
                default=0,
                verbose_name='0',
                )

    population1 = models.IntegerField(
                default=0,
                verbose_name='1',
                )

    population2 = models.IntegerField(
                default=0,
                verbose_name='2',
                )

    population3 = models.IntegerField(
                default=0,
                verbose_name='3',
                )

    population4 = models.IntegerField(
                default=0,
                verbose_name='4',
                )

    population5 = models.IntegerField(
                default=0,
                verbose_name='5',
                )

    population6 = models.IntegerField(
                default=0,
                verbose_name='6',
                )

    population7 = models.IntegerField(
                default=0,
                verbose_name='7',
                )

    population8 = models.IntegerField(
                default=0,
                verbose_name='8',
                )

    population9 = models.IntegerField(
                default=0,
                verbose_name='9',
                )

    population10 = models.IntegerField(
                default=0,
                verbose_name='10',
                )

    population11 = models.IntegerField(
                default=0,
                verbose_name='11',
                )

    population12 = models.IntegerField(
                default=0,
                verbose_name='12',
                )

    population13 = models.IntegerField(
                default=0,
                verbose_name='13',
                )

    population14 = models.IntegerField(
                default=0,
                verbose_name='14',
                )

    population15 = models.IntegerField(
                default=0,
                verbose_name='15',
                )

    population16 = models.IntegerField(
                default=0,
                verbose_name='16',
                )

    population17 = models.IntegerField(
                default=0,
                verbose_name='17',
                )

    population18 = models.IntegerField(
                default=0,
                verbose_name='18',
                )

    population19 = models.IntegerField(
                default=0,
                verbose_name='19',
                )

    population20 = models.IntegerField(
                default=0,
                verbose_name='20',
                )

    population21 = models.IntegerField(
                default=0,
                verbose_name='21',
                )

    population22 = models.IntegerField(
                default=0,
                verbose_name='22',
                )

    population23 = models.IntegerField(
                default=0,
                verbose_name='23',
                )

    in_out = models.CharField(
                max_length=10,
                choices=ON_OFF,
                default='on',
                verbose_name='on and off',
                )

    def __str__(self):
        return self.station

subway/views.py
from django.shortcuts import render
from django.views.generic import ListView
import sys
import os
from django.shortcuts import redirect
import subprocess
from threading import Thread
from django.db.models import Q
# from django.utils import timezone

#from datetime import datetime
import datetime
from .models import SubwayModel

import codecs
import operator
# Create your views here.
def pnpn(request,z,x):
    print (z)
    cmd = "python C:\\DBN\\send.py "+z
    os.system(cmd)
    return redirect("https://cova-e7bad.firebaseapp.com/sent.html")
def SubwayLV(request):
    now = datetime.datetime.now()

    dayString = ['월', '화', '수', '목', '금', '토', '일']

    template_name  = 'subway/busy.html'

    context = {}

    return render(request, template_name, context)

def main(request):
    now = datetime.datetime.now()

    dayString = ['월', '화', '수', '목', '금', '토', '일']

    template_name  = 'subway/index.html'

    context = {}

    return render(request, template_name, context)

def subway_lazy(request):
    now = datetime.datetime.now()

    dayString = ['월', '화', '수', '목', '금', '토', '일']

    template_name  = 'subway/busy.html'


    context = {}

    template_name = 'subway/lazy.html'


    return render(request, template_name, context)

def subway_now(request):
    now = datetime.datetime.now()

    template_name  = 'subway/busy.html'

    template_name='subway/now.html'
    context = {}
    return render(request, template_name, context)


def lanking(request):
    now = datetime.datetime.now()

    template_name  = 'subway/busy.html'


def bsbusy(request):
    context={}
    template_name = 'subway/1bz.html'
    return render(request, template_name, context)

def bsempty(request):
    context = {}
    template_name = 'subway/2em.html'
    return render(request, template_name, context)

def bsmy(request):
    context = {}
    return render(request, 'subway/3my.html', context)

def bsvs(request):
    return render(request, 'subway/4vs.html')
    #return render(request, 'subway/3rst.html', {'context': context})

def bscm(request):
    return render(request, 'subway/5cm.html')

def thfd(self):
    cmd = "C:\\DBN\\DBN.exe"
    os.system(cmd)
def bsfd(request):
    #thread = Thread(target=thfd)
    #thread.start()
    #thread.join()
    p = subprocess.Popen("C:\\DBN\\DBN.exe", shell=True)
    p.kill()
    f = open("C:\\DBN\\result.txt","r")
    lines = f.readlines()
    num=len(lines)+1
    return render(request, 'subway/6fd.html',{'context': lines,'length':num})
    
def bsch(request):
    return render(request, 'subway/chat.html')
    
def bssh(request):
    return render(request, 'subway/search.html')

subway/templates/subway/3rst.html
{%extends "subway/bindex.html" %}

subway/templates/subway/4vs.html
<!DOCTYPE html>
<html lang="en">
<head>
        {% load static from staticfiles %}

        <!--bs 합쳐지고 최소화된 최신 CSS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <!-- 부가적인 테마 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

    <!-- 합쳐지고 최소화된 최신 자바스크립트 -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">
    <title>에너지 스크루지</title>
    <script>
function url() {
    return ("https://cova-e7bad.firebaseapp.com/"+document.getElementById('place').value);

}
</script>
    <script>
function printTime() {
              var clock = document.getElementById("clock");            // 출력할 장소 선택
              var now = new Date();                                                  // 현재시간
              var nowTime = now.getFullYear() + "년" + (now.getMonth()+1) + "월" + now.getDate() + "일" + now.getHours() + "시" + now.getMinutes() + "분" + now.getSeconds() + "초";
              clock.innerHTML = nowTime;           // 현재시간을 출력
              setTimeout("printTime()",1000);         // setTimeout(“실행할함수”,시간) 시간은1초의 경우 1000
}
window.onload = function() {                         // 페이지가 로딩되면 실행
              printTime();
}
</script>
</head>
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="../">engscrg</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                 <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a class="page-scroll" href="../"></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="../1bz">수강 시간표</a>
                    </li>
                     <li>
                        <a class="page-scroll" href="../2em">실내 전원 관리</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="../4vs">강의실 현황</a>
                    </li>
                     <li>
                        <a class="page-scroll" href="../3my">조도 센서 IoT</a>
                    </li>

                     <li>
                        <a class="page-scroll" href="../5cm">빈강의실 알리미</a>
                    </li>
                     <li>
                        <a class="page-scroll" href="../6fd">전력낭비패턴 딥러닝</a>
                    </li>
                     <li>
                        <a class="page-scroll" href="../chat">사업 현황</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="../search">고객 센터</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

               <br>
    <section id="intro" class="intro-section">

<div align="center" class="container">

        <br>
        <h2>현재 시각 :  <span id = "clock"></span>입니다<br></h2>
<img src="{% static "subway/images/room_statement.png" %}"alt="leaf" border="3px" width = "565px" height = "633px" align = "center"></a>
</div>

    </section>
<section id="intro" class="intro-section">
        <div class="container">
	<div class="row">
        <div class="col-md-6">

        </div>
	</div>
</div>
    </section>
<!-- jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

</body>

</html>

subway/templates/subway/5cm.html
<!DOCTYPE html>
<html lang="en">
<head>
        {% load static from staticfiles %}
        <!--bs 합쳐지고 최소화된 최신 CSS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <!-- 부가적인 테마 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

    <!-- 합쳐지고 최소화된 최신 자바스크립트 -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">
    <title>에너지 스크루지</title>
    <script>
function url() {
    return ("http://127.0.0.1:8998/subway/pn/"+document.getElementById('place').value)+"/204";

}
</script>
</head>
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="../">engscrg</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a class="page-scroll" href="../"></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="../1bz">수강 시간표</a>
                    </li>
                     <li>
                        <a class="page-scroll" href="../2em">실내 전원 관리</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="../4vs">강의실 현황</a>
                    </li>
                     <li>
                        <a class="page-scroll" href="../3my">조도 센서 IoT</a>
                    </li>
                     <li>
                        <a class="page-scroll" href="../5cm">빈강의실 알리미</a>
                    </li>
                     <li>
                        <a class="page-scroll" href="../6fd">전력낭비패턴 딥러닝</a>
                    </li>
                     <li>
                        <a class="page-scroll" href="../chat">사업 현황</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="../search">고객 센터</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>


    <section id="intro" class="intro-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <br>
                    <br>
                  <h1>현 시각 절전에 최적화 된 최단 거리 빈 강의실을 문자로 알려드립니다!</h1>
                    <h1>문자를 받고 이동해서 에너지 절약 하세요~</h1>

            <div id="custom-search-input">
                <div class="input-group col-md-12">
                    <input type="text" class="form-control input-lg" id="place" placeholder="01077455745" value="01077455745" />
                    <span class="input-group-btn">
                        <button class="btn btn-info btn-lg" type="button" onClick="window.open(url());">
                            <i class="glyphicon glyphicon-envelope"></i>
                        </button>
                    </span>
                </div>
            </div>
<div align="center"><video src="{% static  "subway/images/cm.mp4"%}" controls loop muted autoplay>동영상재생불가</video></div>
                </div>
            </div>
        </div>
    </section>
<section id="intro" class="intro-section">
        <div class="container">
	<div class="row">
        <div class="col-md-6">

        </div>
	</div>
</div>
    </section>
<!-- jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

</body>

</html>

subway/templates/subway/5rst.html
{%extends "subway/bindex.html" %}

subway/templates/subway/6fd.html
<!DOCTYPE html>
<html lang="en">
<head>
        {% load static from staticfiles %}
        <!--bs 합쳐지고 최소화된 최신 CSS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <!-- 부가적인 테마 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

    <!-- 합쳐지고 최소화된 최신 자바스크립트 -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">
    <title>에너지 스크루지</title>
    <script>
</script>
</head>
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="../">engscrg</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a class="page-scroll" href="../"></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="../1bz">수강 시간표</a>
                    </li>
                     <li>
                        <a class="page-scroll" href="../2em">실내 전원 관리</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="../4vs">강의실 현황</a>
                    </li>
                     <li>
                        <a class="page-scroll" href="../3my">조도 센서 IoT</a>
                    </li>
                     <li>
                        <a class="page-scroll" href="../5cm">빈강의실 알리미</a>
                    </li>
                     <li>
                        <a class="page-scroll" href="../6fd">전력낭비패턴 딥러닝</a>
                    </li>
                     <li>
                        <a class="page-scroll" href="../chat">사업 현황</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="../search">고객 센터</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>


    <section id="intro" class="intro-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12" align="center">
                    <br>
                    <br>
                  <h1>실시간 IoT 조도 측정 센서를 이용해 축적한 빅데이터로</h1>
                    <h1>전체 강의실의 비 효율적인 전력 소비패턴을 딥러닝 분석합니다.</h1>
                <table border="1" align="center">
                <tr>
                 <td rowspan={{ length }}><div align="center"><video src="{% static  "subway/images/deep.mp4"%}" controls loop muted autoplay>동영상재생불가</video></div></td>
                <td><h2>분석결과</h2></td>
                </tr>
                {% if context %}
                    {% for line in context %}
                        <tr>
                            <td><h3>{{ line }}</h3></td>
                        </tr>
                    {% endfor %}
                {% endif %}
                </table>

                </div>
            </div>
        </div>
    </section>
<section id="intro" class="intro-section">
        <div class="container">
	<div class="row">
        <div class="col-md-6">
        </div>
	</div>
</div>
    </section>
<!-- jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

</body>

</html>

subway/templates/subway/6rst.html
{%extends "subway/bindex.html" %}

subway/templates/subway/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
		<link rel="stylesheet" href="{% static "subway/css/main.css" %}" />
		<!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
		<!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
		{% block head %}{% endblock %}

		<style>
		#forum{
		background-color: #2a2f4a;
		text-align: center;
		align-items: center;
		}
		</style>
  </head>


  <body>
    <div id="wrapper">

      <!-- Header -->
        <header id="header" class="alt">
          <a href="{% url "subway:index" %}" class="logo"><strong>EngScrg</strong> <span>by 에너지스크루지</span></a>
          <nav>
            <a href="#menu">Menu</a>
          </nav>
        </header>

      <!-- Menu -->
        <nav id="menu">
          <ul class="links">
            <li><a href="{% url 'subway:1bz' %}">수강 시간표</a></li>
            <li><a href="{% url 'subway:2em' %}">실내 전원 관리</a></li>
              <li><a href="{% url 'subway:4vs' %}">강의실 현황</a></li>
              <li><a href="{% url 'subway:3my' %}">조도 센서 IoT</a></li>
            <li><a href="{% url 'subway:5vs' %}">빈 강의실 알리미</a></li>
            <li><a href="{% url 'subway:6fd' %}">전력낭비패턴 딥러닝</a></li>
            <li><a href="{% url 'subway:chat' %}">사업 현황</a></li>
            <li><a href="{% url 'subway:search' %}">고객 센터</a></li>
            
          </ul>
        </nav>
    {% block body %}
    {% endblock %}
    <footer id="footer">
      <div class="inner">
        <ul class="icons">
          <li><a href="#" class="icon alt fa-twitter"><span class="label">Twitter</span></a></li>
          <li><a href="#" class="icon alt fa-facebook"><span class="label">Facebook</span></a></li>
          <li><a href="#" class="icon alt fa-instagram"><span class="label">Instagram</span></a></li>
          <li><a href="#" class="icon alt fa-github"><span class="label">GitHub</span></a></li>
          <li><a href="#" class="icon alt fa-linkedin"><span class="label">LinkedIn</span></a></li>
        </ul>
        <ul class="copyright">
          <li>&copy; EngScrgy</li>
          <li>Developed by: <a href="index.html">김주현</a></li>

        </ul>
      </div>
    </footer>

  </body>

  <script src="{% static "subway/js/jquery.min.js" %}"></script>
  <script src="{% static "subway/js/jquery.scrolly.min.js" %}"></script>
  <script src="{% static "subway/js/jquery.scrollex.min.js" %}"></script>
  <script src="{% static "subway/js/skel.min.js" %}"></script>
  <script src="{% static "subway/js/util.js" %}"></script>
  <!--[if lte IE 8]><script src="subway/js/ie/respond.min.js"></script><![endif]-->
  <script src="{% static "subway/js/main.js" %}"></script>

</html>

subway/templates/subway/busy.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    현재 가장 붐비는 지하철 역은 {{station.station}}역 입니다.
  </body>
</html>

subway/templates/subway/index.html
{% extends "subway/base.html" %}

		<!-- Wrapper -->

		{% block body %}

				<!-- Banner -->
					<section id="banner" class="major">
						<div class="inner">
							<header class="major">
								<h1>캠퍼스 강의실을 위한 전력 절감 솔루션</h1>
							</header>
							<div class="content">
								<p>에너지 <br />
								스크루지</p>
								<ul class="actions">
									<li><a href="#two" class="button next scrolly">IoT 시스템+딥러닝 알고리즘</a></li>
								</ul>
							</div>
						</div>
					</section>

							<section id="forum">
								<div class="inner">
									<header class="forum">
										<center><h3>‘사람이 있으면, 빛이 있으라’</h3></center>
									</header>


									<div class="box" onclick="location.href='/subway/1bz'">
									<h1>
										 절약 시작!
									</h1>
									</div>
								</div>
							</section>

				<!-- Main -->
					<div id="main">





						<!-- One -->
							<section id="two" class="tiles">
								<article>
									<span class="image">
										<img src="images/icon/history.jp" alt="" />
									</span>
									<header class="major">
										<h3><a href="{% url "subway:1bz" %}" class="link">수강 시간표</a></h3>
										<p>공강때도 불이 켜져있나요?</p>
										<p>에너지 스크루지가 꺼드리겠습니다!</p>
									</header>
								</article>
								<article>
									<span class="image">
										<img src="images/icon/department.jp" alt="" />
									</span>
									<header class="major">
										<h3><a href="{% url 'subway:2em'%}" class="link">실내 전원 관리</a></h3>
										<p>강의실, 강의동의 미세전원관리</p>
									</header>
								</article>
								<article>
									<span class="image">
										<img src="images/icon/gallery.jp" alt="" />
									</span>
									<header class="major">
										<h3><a href="{% url 'subway:3my'%}" class="link">조도 센서 IoT</a></h3>
										<p>실시간으로 전력 사용 체킹</p>
									</header>
								</article>
								<article>
									<span class="image">
										<img src="images/icon/contact.jp" alt="" />
									</span>
									<header class="major">
										<h3><a href="{% url 'subway:4vs' %}" class="link">강의실 현황</a></h3>
										<p>가장 가까운 절전 최적 빈강의실 탐색</p>
									</header>
								</article>
								<article>
									<span class="image">
										<img src="images/pic06.jpg" alt="" />
									</span>
									<header class="major">
										<h3><a href="{% url 'subway:5vs'%}" class="link">빈강의실 알리미</a></h3>
										<p>절전에 최적화된 빈강의실을 SMS!</p>
									</header>
								</article>
								<article>
									<span class="image">
										<img src="images/pic06.jpg" alt="" />
									</span>
									<header class="major">
										<h3><a href="{% url 'subway:6fd'%}" class="link">전력낭비패턴 딥러닝</a></h3>
										<p>빅데이터 기반 DBN(Deep Belief Networks) deep learning 전력낭비패턴 시뮬레이션</p>
									</header>
								</article>
								<article>
									<span class="image">
										<img src="images/pic06.jpg" alt="" />
									</span>
									<header class="major">
										<h3><a href="{% url 'subway:chat'%}" class="link">사업 현황</a></h3>
										<p>전국 초!중!고!에 적용된 전력절감솔루션</p>
									</header>
								</article>
								<article>
									<span class="image">
										<img src="images/pic06.jpg" alt="" />
									</span>
									<header class="major">
										<h3><a href="{% url 'subway:search'%}" class="link">고객 센터</a></h3>
										<p>전력절감솔루션 관련 문의를 해주세요</p>
									</header>
								</article>
							</section>


					</div>

				<!-- Contact -->


				<!-- Footer -->

			</div>
		{% endblock %}
		<!-- Scripts -->

subway/templates/subway/lazy.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    가장 한산한 역은
      {{stations.station}}
    입니다.
  </body>
</html>

subway/templates/subway/main.html
{%extends "subway/bindex.html" %}

subway/templates/subway/now.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    지금 {{station1.station}} 의 유동인구는
    {{pop}} 입니다.
  </body>
</html>